### ISSUE TITLE
Unable to search "All collections" in chat if a Collection exists with no Documents

### ISSUE THREAD

**Issue by oxaronick** [nickthecook/archyve#55]
1. Create a Collection, don't add any docs
2. Chat with "All collections" selected

This should reproduce it, but if not, create two Collections, one with docs and one without.

```
jobs   | Chromadb::ResponseError: {"detail":"Not Found"}/Users/nick/src/github.com/nickthecook/archyve-main/app/lib/chromadb/client.rb:123:in `post'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/lib/chromadb/client.rb:60:in `query'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/search/chromadb_query.rb:49:in `response'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/search/chromadb_query.rb:18:in `fetch_results'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/search/chromadb_query.rb:10:in `results'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/search/search.rb:27:in `chroma_results_for'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/search/search.rb:15:in `search'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/search/search_n.rb:14:in `block in search'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/search/search_n.rb:13:in `map'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/search/search_n.rb:13:in `search'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/reply_to_message.rb:124:in `prompt_augmentor'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/reply_to_message.rb:42:in `augment_message_prompt'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/services/reply_to_message.rb:14:in `execute'
jobs   | /Users/nick/src/github.com/nickthecook/archyve-main/app/sidekiq/reply_job.rb:11:in `perform'
```

**Comment by oxaronick** [comment]
Fixed in `main`.
