### ISSUE TITLE
Missing open3 gem

### ISSUE THREAD

**Issue by mattlindsey** [nickthecook/archyve#81]
Adding a pdf document gives me the error below, which I resolved by adding `gem "open3"` to Gemfile. Ruby 3.1.4.
Maybe adding `require "open3"` would also fix it.
```
jobs    | 2024-09-18T21:28:30.248Z pid=59558 tid=ohq WARN: NameError: uninitialized constant Parsers::Pdf::Open3
jobs    |
jobs    |       txt, stderr, status = Open3.capture3(cmd, stdin_data: @document.contents, binmode: true)

**Comment by nickthecook** [comment]
Cool, is it a PDF you can share?

I've not seen that error; assuming it has something to do with the file itself...

**Comment by mattlindsey** [comment]
I tried a few different pdfs and versions of ruby 3 and this PR fixed it #82, although I suppose it's possible it's unique to me.

**Comment by nickthecook** [comment]
Neat, I just added the end-to-end specs but initially didn't exclude them from a normal run of the unit tests. I've fixed that now, so `ops test` shouldn't invoke the e2e specs, and the errors you posted above should be fixed.

The e2e specs are a step towards automating testing but I still haven't solved the data setup, so I'm not sure they'll pass for everyone right now. However, I'm curious what `ops e2e` does on your machine!

**Comment by mattlindsey** [comment]
Cool.  `ops test` is good now.  `ops e2e` gives error below. Something with 'ollama'? ollama is running on my machine.

```
(base) ➜  archyve git:(main) ops e2e
Running `TEST_E2E=true bundle exec rspec --tag "~skip" spec/e2e` in environment 'dev'...
Run options: exclude {:skip=>true}

Randomized with seed 47028

  1) opp/api/tags returns models
     Failure/Error: response = HTTParty.get("#{endpoint}#{path}", headers:)

     Errno::ECONNREFUSED:
       Failed to open TCP connection to localhost:11337 (Connection refused - connect(2) for "localhost" port 11337)
     # ./vendor/bundle/ruby/3.1.0/gems/net-http-0.4.1/lib/net/http.rb:1603:in `initialize'
     # ./vendor/bundle/ruby/3.1.0/gems/net-http-0.4.1/lib/net/http.rb:1603:in `open'

**Comment by nickthecook** [comment]
Good to hear.

11337 is what Archyve's Ollama Proxy Port feature listens. It should be started by a line in `Procfile.dev`, but it sounds like it's not running. That should break more than one test, though - looks like there are 0 OPP tests:

```
$ ops e2e --tag opp
Running `TEST_E2E=true bundle exec rspec --tag "~skip" spec/e2e --tag opp` in environment 'dev'...
Run options:
  include {:opp=>true}
  exclude {:skip=>true}

Randomized with seed 10459
 9/9 |========================== 100 ===========================>| Time: 00:00:36

Finished in 36.89 seconds (files took 0.44331 seconds to load)
9 examples, 0 failures

Randomized with seed 10459
```

**Comment by nickthecook** [comment]
> That should break more than one test, though - looks like there are 9 OPP tests

Oh, it is failing after the first test because I had configured it to do that. I just removed that config. FYI.

**Comment by nickthecook** [comment]
Ah, thanks. Fixed.

When you run `ops server`, do you see lines that start with `opp`? Do you have port 11337 open when the server is running? (Check with `netstat -an | grep LISTEN | grep 11337` on Mac, `netstat ltpn | grep 1137` on Linux, unless you have a preferred way.)

Good stuff - lmk if you have any questions!

**Comment by mattlindsey** [comment]
`opp` runs fine using `ops server`, but doesn't appear to be working on my mac using `ops e2e` since I get the 'Connection refused` error above, but it's not important at the moment.    Everything else looks great.
