### ISSUE TITLE
Error when trying to view an _old_ chat conversation when running Archyve for dev locally

### ISSUE THREAD

**Issue by oxaroky02** [nickthecook/archyve#89]
Error when I switched to Chat in Archyve and clicked one of my _old sessions_. A new conversation opens and works fine. (FYI, I did run db migrate.)

```
web     |   ↳ app/views/messages/_message.html.erb:1
web     |   Rendered shared/_regenerate_button.html.erb (Duration: 0.1ms | Allocations: 119)
web     |   Rendered shared/_copy_button.html.erb (Duration: 0.0ms | Allocations: 10)
web     |   Rendered collection of messages/_message.html.erb [8 times] (Duration: 10.0ms | Allocations: 11435)
web     |   Rendered messages/_form.html.erb (Duration: 1.3ms | Allocations: 2109)
web     |   Rendered conversations/_conversation.html.erb (Duration: 22.1ms | Allocations: 20591)
web     |   Rendered conversations/index.html.erb within layouts/application (Duration: 27.5ms | Allocations: 24520)
web     |   Rendered layout layouts/application.html.erb (Duration: 27.5ms | Allocations: 24611)
web     | Completed 500 Internal Server Error in 50ms (ActiveRecord: 12.3ms | Allocations: 27842)
web     |
web     |
web     |
web     | ActionView::Template::Error (undefined method `upcase' for nil:NilClass
web     |
web     |   hover_text = disable_form ? "This conversation came in through the #{@conversation.source.upcase}, and cannot be edited here." : ""
web     |                                                                                            ^^^^^^^):
web     |     1: <%
web     |     2:   disable_form = @conversation.source != "chat"
web     |     3:   hover_text = disable_form ? "This conversation came in through the #{@conversation.source.upcase}, and cannot be edited here." : ""
web     |     4:   placeholder = disable_form ? "Chat via UI disabled" : "Enter a message"
web     |     5:   button_classes = disable_form ? "bg-secondary-200 dark:bg-secondary-700 text-secondary-400 dark:text-secondary-400" : "text-secondary-100 dark:text-secondary-950 bg-primary-700 dark:bg-primary-500"
web     |     6: %>
web     |
web     | app/views/messages/_form.html.erb:3
web     | app/views/conversations/_conversation.html.erb:14
web     | app/views/conversations/index.html.erb:10
web     | app/controllers/conversations_controller.rb:15:in `block (2 levels) in show'
web     | app/controllers/conversations_controller.rb:11:in `show'
```

**Comment by oxaronick** [comment]
Thanks for the issue. Should be fixed in main now!
